### ISSUE TITLE
In jsPanel2 Require one property to set the status while creating the panel initially

### ISSUE THREAD

**Issue by piu** [Flyer53/jsPanel#16]
Can you provide a property to set the status of the panel while creating? say for e.g I want the panel to be in minimized state initially, so instead of calling the minimize() function separately , can we assign at the initial stage of creating of the jspanel?

**Comment by Flyer53** [comment]
@piu 
I thought about this a bit and can't see a really good reason that justifies extra code since you can achieve this quite easily already:
```javascript
$.jsPanel({
  position: 'center',
  callback: function (panel) {
    panel.minimize();
  }
});
```
And since the callback can be an array of functions it won't limit you in any way.

Ok, this way the panel appears first and than minimizes, maximizes or whatever. But tihis isn't necessarily a disadvantage because you see something happen. Imagine a panel that appears only minimized. Isn't there a good chance that a user might not realize it's there?

What do you think?

**Comment by Flyer53** [comment]
jsPanel version 2.4.0 will have an option corresponding to this issue.
