### ISSUE TITLE
responsive tooltips

### ISSUE THREAD

**Issue by Flyer53** [Flyer53/jsPanel#18]
@devmondo @genachka
I started my first experiments with responsive tooltips and there is a very first example of tooltips shifting left or right when overflowing the window. This first example currently works only as sort of a callback after generating the tooltip:

http://jspanel.de/beta/responsive.html

By default the two buttons generate generate centered tooltips with corners. Now resize the window to a size that makes the tooltips overflow and mouseover again. 

Ideas:
+ tooltips overflowing to the left shift right (but only if there is no additional overflow to the right)
+ tooltips overflowing to the right shift left (but only if there is no additional overflow to the left)
+ shifting of tooltips is limited so that they never loose contact to the triggering element
+ tooltips overflowing both sides don't shift - in this case, I think, the layout should be changed

What do you think?

**Comment by Flyer53** [comment]
@devmondo @genachka @AviHafner

Interested in a beta of version 2.4.0? Grab it here:

http://jspanel.de/downloads/jspanel-2.4.0Beta.zip

or take a look at http://beta.jspanel.de/

What's new:
+ a lot of internal improvements enabling me to remove about 200 lines of code
+ a new **option.maximizedMargin**
+ changed css of header section, header toolbar and footer toolbar essentially making them flexbox-containers. That makes it a lot easier to distribute/align tooltip items and helps a lot with the rtl text direction implementation.

**Comment by devmondo** [comment]
@Flyer53  congrats on new release i l love the micro changes you made to the demo page and  200 of code eliminated that is amazing :)
JSPanel is easly the best in the market no questions :)

i stopped using Angularjs and now i am investing in Aurelia.io, the ES6 forward thinking framework, so amazing, check it out.

also try 6to5.org it makes you write es6 code and compile it yo es5, this will put you in the future with backward compatibility and more lines of code to cut :)

**Comment by Flyer53** [comment]
@devmondo What would I do without all your valuable tips ... :)

I probalby update the 2.4.0 beta this weekend with a new method **reposition(newPosition [, selector])** that repositions an exsisting panel and optionally moves it from one containing element to another.

The use of **flexbox** will not be in the 2.4.0 release. It would kick out IE9 and I don't want to do that yet. Maybe I create a flexbox branch. Especially the RTL integration is so much easier with flexbox features.

**Comment by genachka** [comment]
@Flyer53 - Happy new year to you and yours! Looks like a lot of good additions to jsPanel in the past few months! Excited to play with 2.4.0 (likely next week). Keep it up! ;)

@devmondo - I ended up staying away from Angularjs as I didn't feel it worth the effort to learn when 2.0 would be a a huge redesign/relearn anyway. Not a fan of that approach. Been keeping my eye on Meteor but since I'm a fan of Couchbase and Meteor seems very tied to MongoDB, I've not actually used it anywhere. Aurelia.io is one I've not heard of before. Mind sharing why you chose it over Angularjs?

**Comment by devmondo** [comment]
@Flyer53 
awesome man just trying to give shameful contribution and nothing more :) by the way can we modify the animations? i still feel they are slow or sluggish and sometimes you just dont want animation

@genachka  man, i just got sick of Angular, i have been doing it for the past 2 years and go it enough of the complexity and making simple concepts over complicated, like Directives and services etc...

why i chose Aurelia, well first because of its  creator who is Rob Eisenberg, he is a mastermind and well respected known person in the community plus he is the creator of Durnadaljs, in fact most of what you see in Angularjs 2.0 is his ideas, but he left them because they did not listen to him.

the second thing is that Aurelia is based on ES6 so it is just pure pleasure and you are set in the future while you develop, with the ability of backward compatibility with tools like 6to5.org that compiles es6 to es5.

with aurelia you don't have to think providers, services, etc... everything is just simple Class with metadata.

things like complex directives in angular are just simple in Aurelia, check the following code that i was able to create a redactor.js attachedbehvior in Aurelia which i can apply to any text area and i would have a full htmleditor
```
import {Behavior} from 'aurelia-framework';

export class Editor {
  static metadata() {
    return Behavior
      .attachedBehavior('redactor')
      .withProperty('value', 'valueChanged', 'redactor');
  }

  static inject() {
    return [Element];
  }

  constructor(element) {
    this.element = element
    this.editableArea = $(this.element);
    this.guard = false;
  }

  bind() {
    var _this = this;

    this.editableArea.redactor({
      initCallback: function () {
        this.code.set(_this.value);
      },
      keyupCallback: function (newValue) {
        console.log("1");
        _this.guard = true;
        _this.value =  this.code.get().replace(/<(?:.|\n)*?>/gm, '').replace(/(\r\n|\n|\r)/gm,"");
        setTimeout( () => { _this.guard = false; }, 10);
      }
    });
  }

  valueChanged(newValue) {
    if(!this.guard)
      this.editableArea.redactor('code.set', newValue);
  }

}

```
and to apply it in html just use
```
      <textarea id="content1" name="content1" redactor.two-way="content"></textarea>
```
 of course i got some great help from the people there, but as you see abovethe code is so simple, imagine doing that with Angular directive!!!

also the gitter channel is so active there check it out

https://gitter.im/Aurelia/Discuss

if you need any other info please tell me :) i am never going to go back to Angularjs 1.x

**Comment by Flyer53** [comment]
@devmondo 
Yes I know. I'm not really happy with the animations as well. But, believe me, I don't know how much hours I spent trying to get those animations nice and smooth. Either it's my fault somewhere or the jQuery animations simply don't work better ... I don't know. As far as I see it the only other option would be to remove the animations completely ...

**Comment by Flyer53** [comment]
@devmondo @genachka 

Just uploaded a new beta of 2.4.0 http://beta.jspanel.de/api.html including a download package http://beta.jspanel.de/downloads/jsPanel-2.4.0.zip

The majority of changes happened internally. But there is also a new method **reposition()**, a new **option.panelstatus** and a new property **option**. Just take look and play around a bit if time permits.

If your time permits take a look at #23. Thoughts are welcome :)

**Comment by devmondo** [comment]
@Flyer53  awesome man, you keep making this better, i am rally amazed i wish there were other components like JSPanel that have these options and the will you have to improve.

regarding animation, i say drop jquery animations all together it is sluggish and processor hungry, use css 3 animations, that is the way to go for simple stuff like opacity, position, etc.. trust me it will make things so much easier for you and smoother, and you can make it easily configurable by just exposing a class id so we can define our own animation classes if we want.

**Comment by Flyer53** [comment]
@devmondo 
I removed most of the animations from the current beta. Made a few promising tests with **velocity.js**. But that would mean another dependency.

I don't know whether css3 animation would work. Take the maximize method for example. Size and position have to be calculated each time depending on window size. window scroll position, max within body or element, is maxtoScreen set or not ... I'm not really familiar with css3 animations but can you predefine a class with animations that calculate css property values on the fly when the class is applied to an element???

**Comment by devmondo** [comment]
@Flyer53 

velocity is great, but as you said a new dependency, but i think it can be much simpler, i may be wrong, but the way css animation works is when you apply class animation start, so could you test that when maximize button is clicked, you add the animation calss name pragmatically, and use this animation generator if you want to experiment :)

**Comment by genachka** [comment]
@devmondo 
Thanks for the info! Will definitely look more in to it now. Hopefully it's not a huge learning curve and isn't going to be an almost rewrite soon like Angular 2.0 seems to be. I'm still doing a lot of Play Framework dev so I'm still hoping for something that is easy to learn and doesn't force me to have a lot of extra baggage on the client side that I don't need.
