### ISSUE TITLE
Backdrop removes body's background image

### ISSUE THREAD

**Issue by genachka** [Flyer53/jsPanel#25]
@Flyer53 
I'm experiencing a strange effect. I have a background image and color set on the body. When I open a modal dialog, the backdrop appears and under it I see the body's image and color are gone which makes the rest of the elements on the page look strange. This is with 2.3.3.

**Comment by Flyer53** [comment]
Mmmh, I just tried that myself with 2.3.4 (setting a very colorful background image and a bright green as background color on the body element) and could not reproduce the effect you describe. Tried with FF, Chrome and IE on Windows 8.1. So I actually don't have an idea what could cause this. Do you have an example online where I could see it live?

**Comment by Flyer53** [comment]
Did you do a google search? On first try I found quite a bunch of problems concerning this when the background image is positioned using "fixed" or when using "no-repeat" and a lot of css related things. Especially with Chrome.

**Comment by genachka** [comment]
@Flyer53 
Hmm hadn't encountered that before so didn't think to google that. I am seeing it in chrome and it's a no-repeat. I haven't tried FF yet. Will do a search for that now and try with FF, hopefully there's an easy solve. :)

**Comment by genachka** [comment]
@Flyer53 
Tried in latest FF and same issue. Also why I thought it was jsPanel was that in this particular dialog, it was previously using Colorbox as a modal popup pulling content via Ajax without issue. I only started getting when converted the dialog to use jsPanel instead.

**Comment by Flyer53** [comment]
@genachka 
I did another  search and found dozens of questions related  to disappearing background images in various situations, so I don't think this issue is caused by jsPanel. It seems that image size quite often plays a role.

Try adding:
<code>background-size: "cover";</code>
or
<code>bachground-size: "contain";</code>
to your background image css

**Comment by genachka** [comment]
Unfortunately it doesn't have any change on the background. I did manage to fix it by forcing css classes that seem to be lost to explicitly have values instead of inheriting them. This fixes the issue when jsPanel is opened. It's definetly something to do with jsPanel as when I removed it and put back colorbox and also tried bootbox neither had caused the issue.

**Comment by Flyer53** [comment]
Well, I really would like to help. But since I can't reproduce it on my machine ...

Could it be some kind of side effect with another script?

**Comment by genachka** [comment]
No changes in other scripts. The moment I remove jsPanel and put either colorbox back or try bootbox both work fine. It's very strange and I'm not sure what in jsPanel is causing it, but forcing css classes seems to fix it for now. Basically I have on the main page a css for body that has a background image and color with center center and no-repeat. I open a jsPanel as modal and content comes in from iFrame. The moment jsPanel opens, the main page's body css image gets set to none and the moment jsPanel closes it comes back. Since you can't duplicate it and I have a work around that seems to work I've closed it.

**Comment by Flyer53** [comment]
Thanks for the additional info. I tried it the same way you did. Background image with css "center center no-repeat #123456" and opened a modal panel with an iframe as content. On one hand I'm happy that no problem showed up, on the other hand I still can't reproduce it in order to find something. jsPanel just adds a simple div with a background color and opacity. That's all. But the way you describe it there must be something that overrides the background css. Where does this come from? Just to test .... did you try loading another url in the iframe to see what happens? Does it happen only with iframes as content?

Strange thing ... Well, if you found a way to deal with it ... ok, but still I would like to know what's causing this ...
