### ISSUE TITLE
disable all css animation

### ISSUE THREAD

**Issue by alisabri** [Flyer53/jsPanel#26]
Hi Stefan,

Thank you for your time and effort for this nice plugin. 
My question is, is there any way to disable all css animation (during transition from one state to another e.g opacity change when normalized from minimized state) ?

Best regards,

**Comment by Flyer53** [comment]
Hi there :)
Well, currently I don't have anything built in that disables the animations by default. Would you mind  telling me what the reason is behind your request? Does it intefere with something in your use case?

**Info:** I'm short prior finishing version 2.4.0 and it could well be that I remove most of the animations anyhow within 2.4.0

**Comment by Flyer53** [comment]
Just took a quick look at coming version 2.4.0 code. The "normalize" method won't have an animation anymore. But "minimize", "smallify" up & down and repositioning of minimized panels will use jquery animate. It really wouldn't look good without the animations.

2.4.0 Beta preview: http://beta.jspanel.de/
Beta download: http://beta.jspanel.de/downloads/jsPanel-2.4.0.zip

**Comment by alisabri** [comment]
Hi Stefan, 
Actually it does not interfere with any thing, the reason was, I am using your plugin to display images which will be produced by server side algorithms, so the notion of display speed might matter for the users. But its not a big deal I have already shortened 'duration' in css animation and try 2.4.0 now. Thanks for the quick response.

Regards

**Comment by Flyer53** [comment]
I just updated the 2.4.0 beta. It's now possible to disable the "entry" animation when creating a new panel by setting option.show to false:
```javascript
$.jsPanel({
    show: false
});
```
Could be something you might want to use ...

**Comment by alisabri** [comment]
That is great
Thank you Stefan

**Comment by Flyer53** [comment]
You're welcome!
I have a request too: In case there is something publicly available I would appreciate getting a link. Not that I want to control anything, just to see how you use jsPanel. That would help me lot with improving the plugin and getting ideas for future versions.

**Comment by alisabri** [comment]
Hi Again,
Of course, I will let you know as soon as I finish

Regards

**Comment by alisabri** [comment]
Hi Stefan,

I used jsPanel in my project, tide. It is an online Lua REPL. You can checkout here :
https://github.com/bitradio/tide

thanks,

Regards,
Ali Sabri Sanal

**Comment by Flyer53** [comment]
Hi Ali,

thanks for the info :)
Is there a live demo somewhere? Would be nice for your GitHub repo as well.

BTW: I have an early alpha version online of a possible jsPanel 3.0. http://beta.jspanel.de/
But works currently only with FF or EDGE due to the used ES6 features. Nevertheless you might want to take a look.

Regards, Stefan

**Comment by alisabri** [comment]
Hi Stefan,
You are right, a live demo would be nice. I will try to arrange something.
No I havent try version 3.0. I will check it out.

Regards, Ali

**Comment by AviHafner** [comment]
Hello  Stefan
Please check the version 3.00 of jsPanel in internet explorer 11.
It seems to me   that this version does not work in internet explorer 11.


Regards , Avi

**Comment by Flyer53** [comment]
@AviHafner 
Hi Avi,
you're correct. Currently only FF and EDGE support the required ES6 features for this early Alpha version of jsPanel 3 which uses arrow functions, template literals, object shorthand methodes and Array.prototype.find

And since Windows 10 is coming soon I don't think MS will ever upgrade IE11 to support ES6

Regards, Stefan

**Comment by AviHafner** [comment]
Hi Stephen
I am working with Windows 10 and edge Browser
And getting in Jspanel strange results.
Regards , Avi

**Comment by Flyer53** [comment]
OK Avi, my statement that the jsPanel 3 Alpha works on EDGE is just based on an ES6 compatibility list. I didn't try myself yet because I do all the testing on FF so far. For the time being it's strictly experimental anyhow ...
