### ISSUE TITLE
Minimum example...

### ISSUE THREAD

**Issue by samcov** [Flyer53/jsPanel#33]
I thought I had the minimum example, but for some reason the resize element that should be on the lower right, is on the lower left, and of course doesn't work.

Which javascript file controls that? I'm loading the following in the head, but also tried the body.

//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js
source/jquery.jspanel.js

**Comment by Flyer53** [comment]
Hi there,
resizer position is controlled by the css file of the jQuery-UI library. Please take a look at issue #30 where the same problem is described and solved by

**"... Adding float:right to .ui-resizable-handle.ui-resizable-se.ui-icon.ui-icon-gripsmall-diagonal-se puts it in the correct position."**

Since I couldn't reproduce this issue I ask you to tell me what other javascripts/libraries you load into your page. Maybe I'm able then to find some unwanted side effect ...

**Comment by samcov** [comment]
As I said, I wanted the **minimum** possible, so the ones I listed are the **only** libraries I loaded, not even jquery-ui css.

However, I made that change in the css, and everything is fine. I just hate to load things I don't need, so minimal requirements are generally the first test for me.

Thanks for the assist!
