### ISSUE TITLE
forEach() not working in IE8

### ISSUE THREAD

**Issue by apmsoso** [Flyer53/jsPanel#41]
Hi! what can I do about this?
file :  jquery.jspanel.min.js  :  [b,b.header,b.content,b.footer].forEach(function(a){c(a)....

**Comment by Flyer53** [comment]
Hi there!
You could try to use a ployfill for **forEach()** as described here:
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Polyfill
But I doubt that will make jsPanel work properly on an IE8 since there are some more things like CSS3 style declarations IE8 won't recognize.

And please note that I don't make any effort to support browsers prior IE9.

**Comment by apmsoso** [comment]
Thx !
I used the ployfill code, it works, but it made another issue on IE8: the panel stretched down Infinitely.

**Comment by Flyer53** [comment]
Sorry! As I said, there are quite a few css3 styles IE8 doesn't know like: rgba colors, opacity, gradients, shadows, box-sizing. Then there also is css **calc()** I use which IE8 can't handle either.
And remember that jquery doesn't support browsers < IE9 as of jquery 2.x

**Comment by apmsoso** [comment]
got it ,Thx again!
