### ISSUE TITLE
Minimize / Maximize reload iframe

### ISSUE THREAD

**Issue by diedona** [Flyer53/jsPanel#43]
Hello,

First of all: thanks for the great effort into this plugin. It's being really helpful.

I am working with an iframe inside the panel. In the iframe i have a report which has a great server side processing. I noticed that when i minimize the panel, the iframe gets reloaded, so the processing occurs three times (first for the openning, second for the minimize, third for openning again).

As far as i've seen, this is not a real issue with the plugin, but with how the plugin manage its content.

```javascript
    movetoMinified: function (panel) {
        // wenn der Container für die minimierten jsPanels noch nicht existiert -> erstellen
        if ($('#jsPanel-min-container').length === 0) {
            $('body').append('<div id="jsPanel-min-container"></div>');
        }
        if (panel.status !== "minimized" || panel.option.panelstatus !== "minimized") {
            // jsPanel in vorgesehenen Container verschieben
            panel.css({
                left: ($('.jsPanel', '#jsPanel-min-container').length * jsPanel.widthForMinimized),
                top: 0,
                opacity: 1
            })
                .appendTo('#jsPanel-min-container') // <--- this seems to be the 'evil'
                .resizable({disabled: true})
                .draggable({disabled: true});
            panel.trigger('jspanelminimized', panel.attr('id'));
            panel.trigger('jspanelstatechange', panel.attr('id'));
        }
    }
```

Currently i am hacking my way trying to only make a repositioning rather than an DOM manipulation. Would this be ok?

BTW: I'm using content and positioning the iframe inside with an string concatenated. But i could reproduce the problem using the iframe examples of the demos.

**Comment by Flyer53** [comment]
Hi there ... and thanks for your input :)

Yep! I fully agree with you. Your remark <i>// <--- this seems to be the 'evil'</i> points exactly to the critical issue and I'm not happy with it either. I guess because the panel is first removed and than inserted again the source is processed again, effectively reloading the complet content again. Same with option.load and option.ajax btw. At the time I implemented the minimize feature it was simply the way I could get it done with my somewhat limited capabilities as amateur programmer. If you find a solution that works better for you ... go ahead and do it.

Currently I'm planning and making first tests for a version 3 of jsPanel. Among other things like using some ES6 and removing the dependency on jQuery-UI I definitely want to do without this extra container to move the minimized panels to.

At the moment I focus on writing a new positioning "engine", a no-jquery-ui dragable function and more pure JavaScript - less jQuery. What I'm stiil looking for is a replacement for jQuery-UI resizable.

I'm always grateful for tips/ideas to improve jsPanel. So don't hesitate to tell me what you think ...

Have a nice weekend, Stefan

**Comment by diedona** [comment]
Hello again!

I've submitted a pull request (https://github.com/Flyer53/jsPanel/pull/44), we have been using a variation of this at our project.

We haven't had a lot of time to test, since the customer needed it ASAP on Friday... I have never made a jQuery plugin, so i tried to copy your style. I hope it can be somewhat usefull =)

Btw, your code style and hability are great! By no means i think it's "amateur" :+1:

**Comment by Flyer53** [comment]
I'm working on version 3 of jsPanel and it's close to a Beta status.
The issue you described above will not an issue anymore with jsPanel version 3 because it handles the minimizing process different.
