### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by andreschardong** [Flyer53/jsPanel#47]
First of all, awesome plugin! Thanks!!
I was having issues with position: { top: "auto", rigth: "auto" }. When top = 0, the position object, panelpos was returning {bottom: NaN, right: NaN}, instead of {top: 0, right: 0}

Looking the code, two changes solve my issue:
- including panelpos.top = jsP.option.position.top; after this.calcPos('top', jsP); and
- including                  panelpos.left = jsP.option.position.left; after this.calcPos('left', jsP);

everything works fine now. is this correct? Or am I missing something.

**Comment by Flyer53** [comment]
Hi there ... and thanks for the praise :)

Thank you very much for your report. And yes, there is an issue with using **position: { top: "auto", rigth: "auto" }**. Noticed this myself a few days ago but didn't have time to investigate it ... working to much on jsPanel version 3 ;)

Your solution seems to work fine but instead of adding 2 lines of code I would just change the two lines to:
```javascript
panelpos.top = this.calcPos('top', jsP);
```
and
```javascript
panelpos.left = this.calcPos('left', jsP);
```
respectively.

But this needs some more testing before I release a fixed version. If your time permits maybe you can make some tests as well. Would appreciate that and some feedback very much.

Thanks again, Stefan

**Comment by Flyer53** [comment]
This issue is fixed with version 2.5.4

**Comment by andreschardong** [comment]
Dear Stefan, I see you released the fix. Thank you so much. Everything is working fine!

**Comment by Flyer53** [comment]
@andreschardong 
I have to thank you!
Not only for reporting, but also for providing the solution as well :)
