### ISSUE TITLE
bootstrap3 btn-group-justified in footer

### ISSUE THREAD

**Issue by RobWalker** [Flyer53/jsPanel#49]
I have a panel which I'm using with Bootstrap 3 and the toolbarFooter option to add HTML as a string.

If I inject buttons it works great:
![image](https://cloud.githubusercontent.com/assets/736849/10380913/dfe3527e-6de4-11e5-8d23-20e19eb07150.png)

But if I add .btn-group-justified to the div containing the buttons in order to stretch them across the bottom of the panel I get very odd behaviour: the right hand edge of the panel gets anchored to the right hand side of the screen and attempting to move the panel results in it resizing horizontally instead as the right hand side stays anchored

![image](https://cloud.githubusercontent.com/assets/736849/10380961/3df8c61e-6de5-11e5-876e-fafd4795f4ba.png)

Any ideas?  Thanks!

**Comment by Flyer53** [comment]
Hi Rob,
thanks for reporting this issue ... confirmed.
Also the option.position shorthand string values don't work when using .btn-group-justified. Some time back I had exactly the issue you discribed. I thought it's caused by some strange inner working of jQuery UI and I could fix it by explicitly assigning width to the panel itself. With option.size you only define size of the content section. Now in my tests I saw that - for whatever reason - this step is not happening when using .btn-group-justified. So I just added a callback to catch up on this and it seems to work ... at least in my example as shown below
```javascript
var footer = '<div style="padding-right:5px;" class="btn-group btn-group-justified" role="group">' +
            '<div class="btn-group" role="group">' +
                        '<button type="button" class="btn btn-primary">One</button>' +
                    '</div>' +
                    '<div class="btn-group" role="group">' +
                        '<button type="button" class="btn btn-success">Two</button>' +
                    '</div>' +
                    '<div class="btn-group" role="group">' +
                        '<button type="button" class="btn btn-warning">Three</button>' +
                    '</div>' +
                    '<div class="btn-group" role="group">' +
                        '<button type="button" class="btn btn-info">Four</button>' +
                    '</div>' +
            '</div>';
var test = $.jsPanel ( {
  toolbarFooter: footer,
  callback: function (panel) {
        panel.css( {width: function () { return panel.content.css('width') } } );
  }
} );
```
But still option.position shorthand strings don't work when using .btn-group-justified :(

Could you please check whether adding this callback helps in your usecase and tell me?

Finding out the core problem behind this is probably some more work ...

**Comment by Flyer53** [comment]
Just checked with jsPanel 3 Alpha. Seems not to be an issue here ...
Live example: http://beta.jspanel.de/btn-group-justified.html

**Comment by RobWalker** [comment]
Great -- thanks for the fast reply.

Adding the callback to set the width worked just fine.  The buttons spread across the bottom and the panel doesn't anchor itself to the right.

Looking forward to using jsPanel 3.  Appreciate your work on a great library.
