### ISSUE TITLE
Disable animation if initial panel status is minimized

### ISSUE THREAD

**Issue by gorgi** [Flyer53/jsPanel#50]
I'm using jsPanel 2.5.5. I'm using the following properties:

$.jsPanel({
...,
panelstatus: "minimized"
show: false
}

and still the panel shows briefly and then fades out to minimized state. The expected behavior would be not to display it at all, but have it minimized initially.

Is there anyway to disable animation fully?

Thanks

**Comment by Flyer53** [comment]
Hi there,
Well, I'm aware of this issue and it's not caused by the animation. Though I couldn't find a satisfying solution to this yet. But I have a workaround that might work for you:
```javascript
$.jsPanel({
    panelstatus: "minimized",
    callback: function() {
        this.css('left', '-9000px');
        this.option.position.left = 0;
    }
});

// or

$.jsPanel({
    panelstatus: "minimized",
    position: { left: 100, top: 50 },
    callback: function() {
        this.css('left', '-9000px');
        this.option.position.left = 100;
    }
});
```
So just create the jsPanel as desired but use the callback to:
+ immediately move the panel off screen using css left (this seems to happen fast enough that you don't see the panel before it's off screen)
+ and then update option.position.left to the value you initially wanted the panel to have so it's at the correct position when restored from minimized

This will not work with all possible positioning options. You have to test.

Btw: This seems not to be an issue with jsPanel 3 Alpha: http://beta.jspanel.de/api/option/setstatus
