### ISSUE TITLE
option for external zIndex function

### ISSUE THREAD

**Issue by gbaumgart** [Flyer53/jsPanel#63]
hi,
I am missing the possibility to handle the zIndex increment from outside. I tried  to set it via css but somehow it fails. Could you add this to the options please, as function.
thanks a lot

**Comment by Flyer53** [comment]
Hi again,
Let me explain something first. The very first jsPanel in the document gets a z-index of <code>100</code>. For each new panel z-index is increased by <code>1</code>. And whenever you click on a panel its z-index is increased in order to bring the panel to the top. So your approach failed because z-index is managed by the script.
You could set your own z-index after creating the panel like this:
```javascript
$.jsPanel().css("z-index", 150);
```
or using the callback:
```javascript
$.jsPanel({
  callback: function(panel){
    panel.css("z-index", 150);
  }
});
```
But this would still get a panel to the front if clicked on.
Would this work for you? Or do you need the click handler disabled as well?

**Comment by gbaumgart** [comment]
yes, that would do too, didn't think about the final callback. thanks again for the heads up!
